#! /bin/bash
#***********************************************************************
# file: arkologic_rsync
# date: 2013-08-07 14:56
# author: (c) by Eric Yuan - <ericy@arkologc.com>
# description: rsync a file/dir to a specific locatoin in a remote server
# ***********************************************************************

if [ "$#" -ne 3 ]
then
  echo "Usage:arkologic_sync_all [host] [local_path] [remote_path]"
  exit 1
fi
lpath="$2"
rpath="$3"
[ -d $2 ] && {
  lpath=${lpath%/}\/
}
[ -d $3 ] && {
  rpath=${rpath%/}\/
}
/usr/bin/rsync -Pvaz  --progress --delete-excluded --rsh "ssh -o StrictHostKeyChecking=no " --recursive --rsync-path "rsync" "$lpath" root@$1:"$rpath"
